version: "3.9"
services:
  server:
    build: .
    command: /bin/ash -c "rm -f tmp/pids/server.pid && bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundler_cache:/usr/local/bundle/ # Don't forget to remove the volume after update Gemfile
      - node_modules:/app/node_modules    # Don't forget to remove the volume after update modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
    environment:
      POSTGRES_PASSWORD: epitech
      POSTGRES_USER: epitech

volumes:
  postgres:
  bundler_cache:
  node_modules: