default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: epitech
  password: epitech
  host: postgres

development:
  <<: *default
  database: epitech_dev

test:
  <<: *default
  database: epitech_test

